In [4]:
import numpy as np

In [32]:
a = np.array([0, 0, 0, 1, 0])
w = np.random.randint(0, 10, size=(len(a), 4))

In [33]:
a

array([0, 0, 0, 1, 0])

In [34]:
w

array([[2, 3, 3, 5],
       [1, 4, 0, 0],
       [4, 2, 5, 1],
       [3, 2, 5, 2],
       [9, 3, 4, 7]])

In [35]:
o = a.dot(w)

In [36]:
o

array([3, 2, 5, 2])

In [37]:
o / o.sum()

array([0.25      , 0.16666667, 0.41666667, 0.16666667])

In [38]:
a

array([0, 0, 0, 1, 0])

In [39]:
o / o.sum()

array([0.25      , 0.16666667, 0.41666667, 0.16666667])

In [45]:
input_data = [1, 2, 3, 4, 5, 6]
output_data = ['due', 'uno', 'tre', 'quattro', 'cinque', 'sei']

In [54]:
def encoding(number):
    x = np.zeros(6)
    x[input_data.index(number)] = 1
    return x

def generate_params():
    return np.random.randint(0, 10, size=(len(input_data), len(output_data)))

def activation(data):
    return data / data.sum()

In [68]:
activation(encoding(1).dot(generate_params()))

array([0.23529412, 0.29411765, 0.        , 0.41176471, 0.05882353,
       0.        ])

In [62]:
for i in range(100):
    input_number = np.random.randint(1, 7)
    o = output_data[np.argmax(activation(encoding(input_number).dot(generate_params())))]
    print(input_number, o)
    # calcolare l'errore
    # correggere i parametri
    # usare i nuovi parametri

1 uno
5 quattro
5 quattro
5 sei
5 uno
4 cinque
3 quattro
4 quattro
3 due
6 tre
6 sei
3 quattro
5 uno
3 uno
4 tre
4 tre
4 quattro
2 tre
6 tre
5 due
6 due
4 quattro
3 uno
3 quattro
1 sei
6 cinque
6 quattro
2 uno
6 sei
4 tre
6 quattro
3 cinque
4 cinque
6 sei
6 uno
3 uno
5 sei
4 due
1 uno
2 cinque
3 due
4 quattro
5 due
2 uno
5 uno
2 tre
3 tre
6 quattro
5 quattro
6 quattro
4 sei
4 quattro
2 uno
1 quattro
2 quattro
6 quattro
1 sei
2 quattro
1 cinque
2 uno
1 tre
6 quattro
3 due
2 uno
3 due
1 quattro
5 cinque
1 uno
2 tre
5 tre
2 tre
2 uno
1 tre
4 tre
4 uno
3 quattro
3 sei
3 uno
2 tre
5 quattro
6 uno
4 due
4 sei
5 uno
5 due
6 sei
1 quattro
3 uno
2 uno
2 uno
2 tre
4 uno
2 quattro
2 sei
6 cinque
2 due
3 due
5 tre
2 tre
4 due
